### ISSUE TITLE
Permission denied: '/home/radicale/.config/radicale/collections'

### ISSUE THREAD

**Issue by tomsquest** [jcsaaddupuy/docker-radicale#4]
Running the pull-image-from-docker-hub example, I got a `Permission Denied`.

Full output:

``` shell
$ docker run -p 5232:5232 -v /tmp/radicale/:/data/radicale -i jcsaaddupuy/radicale
Unable to find image 'jcsaaddupuy/radicale:latest' locally
latest: Pulling from jcsaaddupuy/radicale

6e69f355f70e: Pull complete 
a3ed95caeb02: Pull complete 
0f2239bda6b5: Pull complete 
71c6bb5838c5: Pull complete 
f13dcb2174b5: Pull complete 
f97bc9bd371c: Pull complete 
ac3dbcf95b48: Pull complete 
a6b75cfd5b46: Pull complete 
854323d1678b: Pull complete 
76a4a3e11542: Pull complete 
918c9bbccfcb: Pull complete 
Digest: sha256:52d7595ed6790038a7751be6b63d1df294b232576054f0907a8de7d96df29c3c
Status: Downloaded newer image for jcsaaddupuy/radicale:latest
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/radicale/__init__.py", line 331, in __call__
    user)
  File "/usr/local/lib/python2.7/dist-packages/radicale/__init__.py", line 431, in get
    "Creating collection %s" % collection.name)
  File "/usr/local/lib/python2.7/dist-packages/radicale/ical.py", line 452, in name
    return props.get("D:displayname", self.path.split(os.path.sep)[-1])
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/radicale/storage/filesystem.py", line 131, in props
    self._create_dirs()
  File "/usr/local/lib/python2.7/dist-packages/radicale/storage/filesystem.py", line 77, in _create_dirs
    os.makedirs(os.path.dirname(self._path))
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/radicale/.config/radicale/collections'
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/radicale/__init__.py", line 331, in __call__
    user)
  File "/usr/local/lib/python2.7/dist-packages/radicale/__init__.py", line 431, in get
    "Creating collection %s" % collection.name)
  File "/usr/local/lib/python2.7/dist-packages/radicale/ical.py", line 452, in name
    return props.get("D:displayname", self.path.split(os.path.sep)[-1])
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/radicale/storage/filesystem.py", line 131, in props
    self._create_dirs()
  File "/usr/local/lib/python2.7/dist-packages/radicale/storage/filesystem.py", line 77, in _create_dirs
    os.makedirs(os.path.dirname(self._path))
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/radicale/.config/radicale/collections'
```

**Comment by dzervas** [comment]
A "dirty" solution would be to change the permissions through the CMD `chown -R radicale /data/radicale && radicale`.
An even worse solution would be to run radicale as root...

**Comment by tomsquest** [comment]
I did my own version of the Dockerfile to solve this problem. 
See:
- https://hub.docker.com/r/tomsquest/docker-radicale/
- https://github.com/tomsquest/docker-radicale
